backend/routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('admin')->middleware('guest')->name('admin.')->group(function () {
    Route::get('login', array(AuthController::class, 'showLogin'))->name('showLogin');
    Route::post('login', array(AuthController::class, 'login'))->name('login');
});

Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::get('/logout', array(AuthController::class, 'logout'))->name('logout');
    Route::get('/', array(DashboardController::class, 'index'))->name('dashboard');
    Route::get('/logs/{id}', array(DashboardController::class, 'logs'))->name('logs');
    Route::get('/member/{id}/edit', array(DashboardController::class, 'edit'))->name('edit');
});

backend/resources/views/admin/dashboard.blade.php
@extends('admin.layouts')

@section('content')
@verbatim
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Members List
                    </h6>
                </div>
                <div class="card-body">
                    <base-input
                        label="Search"
                        class="col-3 float-right"
                        v-model="search"
                        @input="onFetch"
                    ></base-input>
                    <base-table :data="members" :columns="columns" label-empty="Empty Data">
                        <template slot-scope="{ row }">
                            <td scope="row">{{ row.firstNameTH }}</td>
                            <td scope="row">{{ row.lastNameTH }}</td>
                            <td scope="row">{{ row.firstNameEN }}</td>
                            <td scope="row">{{ row.lastNameEN }}</td>
                            <td scope="row">{{ row.gender }}</td>
                            <td scope="row">{{ row.address }}</td>
                            <td scope="row">{{ row.contactNumber }}</td>
                            <td scope="row">{{ row.email }}</td>
                            <td scope="row">{{ row.idCard }}</td>
                            <td scope="row">{{ row.income * 12 | numberFormat }}</td>
                            <td scope="row">{{ row.tax | numberFormat}}</td>
                            <td scope="row" class="d-flex" style="width: 230px">
                                <a :href="`/admin/logs/${row.id}`">
                                    <button type="button" class="btn btn-sm btn-primary">View Logs</button>
                                </a>
                                <a :href="`/admin/member/${row.id}/edit`">
                                    <button type="button" class="btn btn-sm btn-primary mx-2">Edit</button>
                                </a>
                                <button type="button" class="btn btn-sm btn-primary" @click="onDelete(row.id)">Delete</button>
                            </td>
                        </template>
                    </base-table>
                </div>
            </div>
        </div>
    </div>
@endverbatim
@endsection
@section('script')
<script>
    new Vue({
        el: '#app',
        data() {
            return {
                members: {!! $members->toJson() !!},
                columns: [
                    'firstNameTH',
                    'lastNameTH',
                    'firstNameEN',
                    'lastNameEN',
                    'gender',
                    'address',
                    'contactNumber',
                    'email',
                    'idCard',
                    'inCome',
                    'tax',
                    'action'
                ],
                search: '',
            }
        },
        methods: {
            async onFetch() {
                const { members } = await axios
                                            .get(`/api/member?q=${this.search}`)
                                            .then(({data}) => data);
                this.members = members
            },
            onDelete(id) {
                console.log(id);
                if(confirm('Are you sure delete')) {
                    axios
                        .delete(`/api/member/${id}`)
                        .then(() => {
                            this.onFetch()
                        })
                        .catch(({response}) => {
                            if (response) {
                                console.log(response.data);
                            }
                        })
                }
            }
        },
    })
</script>
@endsection

backend/resources/views/admin/edit.blade.php
@extends('admin.layouts')
@section('content')
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Edit Members
                    </h6>
                </div>
                <div class="card-body">
                    <form class="col-8 mx-auto" @submit.prevent="onUpdate">
                        <div class="row">
                            <base-input
                                class="col-6"
                                label="first Name TH"
                                v-model="member.firstNameTH"
                                :errors="errorState.firstNameTH"
                            ></base-input>
                            <base-input
                                class="col-6"
                                label="last Name TH"
                                v-model="member.lastNameTH"
                                :errors="errorState.lastNameTH"
                            ></base-input>
                        </div>
                        <div class="row">
                            <base-input
                                class="col-6"
                                label="first Name EN"
                                v-model="member.firstNameEN"
                                :errors="errorState.firstNameEN"
                            ></base-input>
                            <base-input
                                class="col-6"
                                label="last Name EN"
                                v-model="member.lastNameEN"
                                :errors="errorState.lastNameEN"
                            ></base-input>
                        </div>
                        <div class="row">
                            <base-select
                                class="col-12"
                                :options="gender"
                                v-model="member.gender"
                                label="gender"
                                :errors="errorState.gender"
                            ></base-select>
                        </div>
                        <div class="row">
                            <base-textarea
                                class="col-12"
                                v-model="member.address"
                                label="Address"
                                :errors="errorState.address"
                            ></base-textarea>
                        </div>
                        <div class="row">
                            <base-input
                                class="col-6"
                                label="contact number"
                                v-model="member.contactNumber"
                                :errors="errorState.contactNumber"
                            ></base-input>
                            <base-input
                                class="col-6"
                                label="email"
                                v-model="member.email"
                                :errors="errorState.email"
                            ></base-input>
                        </div>
                        <div class="row">
                            <base-input
                                class="col-6"
                                label="id card"
                                v-model="member.idCard"
                                :errors="errorState.idCard"
                            ></base-input>
                            <base-input
                                class="col-6"
                                label="monthly income"
                                v-model="member.income"
                                :errors="errorState.income"
                            ></base-input>
                        </div>

                        <button type="submit" class="btn btn-sm btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
<script>
    new Vue({
        el: '#app',
        data() {
            return {
                member: {!! $member->toJson() !!},
                gender: [
                    { value: 'male', label: "male" },
                    { value: 'female', label: "female" }
                ],
                errorState: {}
            }
        },
        methods: {
            onUpdate() {
                const actionBy = {!! Auth::user()->id !!}
                const data = { ...this.member, actionBy }
                delete data.created_at
                delete data.updated_at

                axios
                    .put(`/api/member/${this.member.id}`, data)
                    .then(() => {
                        window.location.href = '/admin'
                    })
                    .catch(({response}) => {
                        if (response) {
                            this.errorState = { ...response.data.errors, ...response.data._error }
                        }
                    })
            }
        },
    })
</script>
@endsection

backend/resources/views/admin/layouts.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('css/sb-admin-2.min.css') }}" rel="stylesheet">

    @yield('css')

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item {{ Request::url() === route('admin.dashboard') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.dashboard') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <!-- <hr class="sidebar-divider"> -->

            <!-- Heading -->
            <!-- <div class="sidebar-heading">
                Interface
            </div> -->

            <!-- Nav Item - Pages Collapse Menu -->
            <!-- <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="buttons.html">Buttons</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li> -->

            <!-- Nav Item - Utilities Collapse Menu -->
            <!-- <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Utilities</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" href="utilities-color.html">Colors</a>
                        <a class="collapse-item" href="utilities-border.html">Borders</a>
                        <a class="collapse-item" href="utilities-animation.html">Animations</a>
                        <a class="collapse-item" href="utilities-other.html">Other</a>
                    </div>
                </div>
            </li> -->

            <!-- Nav Item - Charts -->
            <!-- <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li> -->

            <!-- Nav Item - Tables -->
            <!-- <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
            </li> -->

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid" id="app">

                    <!-- Page Heading -->
                    @yield('content')

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{{ route('admin.logout') }}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/sb-admin-2.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>

    @yield('script')

</body>

</html>

backend/resources/views/admin/logs.blade.php
@extends('admin.layouts')
@section('content')
@verbatim
    <div class="row">
        <div class="col-lg-6 mb-4">
            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Member name {{ member.firstNameEN }} {{ member.lastNameEN }}
                    </h6>
                    <h6 class="m-0 font-weight-bold text-primary">
                        Count Modify {{ member.logs.length }}
                    </h6>
                </div>
                <div class="card-body" v-if="member.logs.length">
                    <div v-for="(log, key) in member.logs" :key="key">
                        <card-list
                            :icon-active="log.id === active"
                            class="mb-2"
                            :data="log"
                            :action-by="log.action_by?.name || `${member.firstNameEN} ${member.lastNameEN}`"
                            @click="viewLogs"
                        >
                        </card-list>
                    </div>
                </div>
                <div class="card-body text-center" v-else>
                    <small class="m-0">Empty Logs</small>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Logs Details</h6>
                </div>
                <div v-if="logsDetail.length" class="card-body">
                    <base-table :data="logsDetail" :columns="columns">
                        <template slot-scope="{ row }">
                            <td scope="row">{{ row.fields }}</td>
                            <td scope="row" class="text-success">{{ row.original }}</td>
                            <td scope="row" class="text-danger" style="text-decoration: line-through">{{ row.old }}</td>
                        </template>
                    </base-table>
                </div>
                <div class="card-body text-center" v-else>
                    <small class="m-0">Empty Logs</small>
                </div>
            </div>
        </div>
    </div>
@endverbatim
@endsection

@section('script')
<script>
    new Vue({
        el: '#app',
        data() {
            return {
                member: {!! $member->toJson() !!},
                columns: [
                    'field',
                    'original',
                    'old'
                ],
                active: {!! count($member->logs) ? $member->logs[0]->id : 0 !!},
                logsDetail: {!! count($member->logs) ? $member->logs[0]->detail->toJson() : '[]' !!},
            }
        },
        methods: {
            viewLogs(id) {
                this.logsDetail = this.member.logs.find(log => log.id === id).detail
                this.active = id
            }
        },
    })
</script>
@endsection